### PR TITLE
Support Python 3 and some additional future/refactors

### PR DESCRIPTION
**Pull request by shahinism**
Hi, 
In these set of commits, I refactored the codebase and added some features to it. Currently implemented features are:

- [x] Python 3 support (And compatible with Python 2.7)
- [x] Bootstrap a Tor instance directly and use it instead of system-wide version (Enables us to add features on customizing Tor itself). 
- [x] Timeout support
- [x] Packaging (No `requirements.txt` and installable through `pip`)
- [x] Install `onioff` script in the user's `PATH`
- [x] Formatted output instead of text files (JSON, TSV)
- [x] Progress bar
- [x] Specific messages for other inactive states (Timeouts, Inaccessible server, SSL Error)

Yet still I plan to develop the following as soon as I have some free time:

- [ ] Unit tests
- [ ] Tox test runner to confirm complete support on all supported Python versions
- [ ] Make SSL verification optional
- [ ] Custom Tor configuration
- [ ] Update Readme

### CODE REVIEW

**Comment by k4m4** [comment]
Hi there @shahinism. Just yesterday I sat and converted ONIOFF to Python 3... 😬 I am planning on pushing it tonight. However, I will look through your code and see if there's any added features that you could push as separate pull-requests to ONIOFF v2.1. Thanks again for your commits! I will look through everything tonight.

**Comment by k4m4** [comment]
@shahinism I have just pushed v2.1. You can create a new pull-request for each added feature, if you'd like. Thanks again!

**Comment by shahinism** [comment]
Hi,
Thank you for your time. I'm not sure if it is possible to port these features to version `2.1` directly. I've moved Tor/Onion related tasks to a separate (more general) module which handles an independent Tor connection (not using system-wide instance and is possible to configure directly). This also reduces the number of requests (No need for IP check). All other features have been developed around this module.

**Comment by k4m4** [comment]
Maybe you could integrate the Tor-handling class within the main script? @shahinism

**Comment by shahinism** [comment]
Well that is what I've already done in this branch 😅 
Before starting this branch, I just wanted to develop some unit tests (for fun) and then add the features I needed for another project (something to continually watch a list of `onion`s and produce programmable results). But to have a testable code base (with separation of concerns) I ended up with applying some general best practices toward having a more Pythonic code base. Actually that `Tor` module is the part that allows having a non-cli interface (something programmable from within another python script), and that is why I added the packaging part.

Anyway, it's entirely cool if you don't like this massive list of changes. You can just deny it, or cherry-pick changes as you wish.

**Comment by k4m4** [comment]
Sounds good. Thank you. :)

**Comment by grubster2020** [comment]
Hello.run scrip error:
python onioff.py -h
Traceback (most recent call last):
  File "onioff.py", line 11, in <module>
    from urllib.request import urlopen
ImportError: No module named request
python3 onioff.py
Traceback (most recent call last):
  File "onioff.py", line 10, in <module>
    import socket, socks, requests, sys, os, time, optparse, datetime, re
ModuleNotFoundError: No module named 'socks'
run the kali linux
Help me please.Thanks.

**Comment by k4m4** [comment]
Hi @grubster2020. `pip3 install pysocks` should solve your issue.

**Comment by shahinism** [comment]
Actually, if you are using this branch, you can try `pip install .` (or `pip install -e .` for development mode) which uses `setup.py` to set it up as a package with command line script in the path `onioff`  (no need to call with python :wink:)

**Pull request closed without merging**
